# Generated by Django 5.1.5 on 2025-01-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mubank_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='ammount',
        ),
    ]
