# Generated by Django 5.1.5 on 2025-01-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubank_api', '0002_rename_value_transaction_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiving_wallet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='mubank_api.wallet'),
        ),
    ]
